language: java

jdk:
  - oraclejdk8

os:
  - linux

branches:
  only:
    - master
    - development

cache:
  directories:
  - $HOME/.gradle

script:
  - ./gradlew clean
  - ./gradlew check
  - ./gradlew assemble
  - ./gradlew build